### ISSUE TITLE
Vorbis AlbumArtist tag

### ISSUE THREAD

**Issue by cassava** [dhowden/tag#22]
From the source file `vorbis.go:179`:
```
func (m *metadataVorbis) AlbumArtist() string {
	// This field isn't included in the standard.
	return ""
}
```

It may not be included in the standard, I have found that many FLAC files nonetheless use the field `albumartist`; this is also supported by a least a few media applications. I haven't done any extensive testing, but it seems to work. Additionally, when converting a FLAC file to MP3, this field is used to populate the ID3 AlbumArtist tag.

I propose therefore to change this to simply return that field.

**Comment by dhowden** [comment]
@cassava Haven't tried #23  it on any files (I don't have any) - would be great if you could verify it!

Assuming there are no problems (or complains from others) I'll merge the pull request.

**Comment by cassava** [comment]
I tried, and it works fine.
