### ISSUE TITLE
Year() not working for ID3v2.4

### ISSUE THREAD

**Issue by humbkr** [dhowden/tag#27]
Hi,

I tagged an mp3 using windows 10 explorer with a year tag = 2017, but calling tags.Year() always returns 0, even as I can read that the correct year is in the Metadata object.

The code:
```
package main

import (
	"os"
	"fmt"
	"github.com/dhowden/tag"
)

func main() {
	file, _ := os.OpenFile("test.mp3", os.O_RDONLY, 0666)
	defer file.Close()

	tags, _ := tag.ReadFrom(file)
	fmt.Println(tags)
	fmt.Println(tags.Format())
	fmt.Println(tags.Year())
}
```

the result:
```
{0xc042002720 map[TPE1:Artist #1 TDRC:2017 TRCK:1 TALB:Artist #1 - Album #1 TIT2:Artist #1 - Album #1 - Track #1 TCON:Genre #1]}
ID3v2.4
0
```

metadataID3v2.Year() seems to be reading the frame TYER and not the frame TDRC in which in my case the year is stored.
This issue is mentionned in https://github.com/dhowden/tag/pull/14 but it seems it has not been fixed.

I attached the mp3 test file.
[test.zip](https://github.com/dhowden/tag/files/1299042/test.zip)

**Comment by dhowden** [comment]
Awesome report + detailed diagnosis,  made it very quick to fix.  Thanks!
