### ISSUE TITLE
panic on bad APICFrame

### ISSUE THREAD

**Issue by thraxil** [dhowden/tag#28]
I've got a file with a stray null byte at the beginning of the mimetype part of the APICFrame. Attempting to read it causes a panic:

    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    github.com/dhowden/tag.readAPICFrame(0xc4200102e0, 0xc, 0xc, 0x4, 0x5ef720, 0x0)
             /home/anders/code/go/src/github.com/dhowden/tag/id3v2frames.go:600 +0x55c
    github.com/dhowden/tag.readID3v2Frames(0x7fc0a37d2fc0, 0xc42000c028, 0xe9, 0xc42000a100, 
    0xc42000c028, 0x0, 0x0)
            /home/anders/code/go/src/github.com/dhowden/tag/id3v2.go:347 +0x796
    github.com/dhowden/tag.ReadID3v2Tags(0x5bbac0, 0xc42000c028, 0x1, 0x0, 0x0, 0x0)
            /home/anders/code/go/src/github.com/dhowden/tag/id3v2.go:405 +0xe0
    github.com/dhowden/tag.ReadFrom(0x5bbac0, 0xc42000c028, 0xc42000c028, 0x0, 0x0, 0x30)
            /home/anders/code/go/src/github.com/dhowden/tag/tag.go:53 +0x2d2

Digging into it a bit, they bytes being passed into `readAPICFrame()` are `00 69 6d 61 67 65 2f 6a 70 65 67 00` which is just `image/jpeg` with a null byte at the beginning and end.

I think the file is invalid so it's fair for the library to refuse to parse it, but it should probably just return an error rather than panicking. It's a pretty simple change to add a `if len(b) < 1` check to `id3v2frames.go` right before line 600.

**Comment by dhowden** [comment]
Thanks for the report - and the fix!
