### ISSUE TITLE
Encoding error reading file

### ISSUE THREAD

**Issue by blimmo** [dhowden/tag#35]
Running this code:
```go
package main

import (
	"log"
	"os"

	"github.com/dhowden/tag"
)

func main() {
	f, err := os.Open("test.mp3")
	if err != nil {
		log.Fatal(err)
	}
	m, err := tag.ReadFrom(f)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(m.Format())
}
```
On the attached file (in a zip to get github to accept it) [test.zip](https://github.com/dhowden/tag/files/1800315/test.zip)

Gives this error:
```
error decoding tag description text: invalid encoding: expected even number of bytes for UTF-16 encoded text
```

The file has non-ASCII characters in the metadata.
I thought it might be a bad file but windows, foobar, etc. are fine with it and displaying its metadata.

**Comment by blimmo** [comment]
Fixed by #36

**Comment by lazaroofarrill** [comment]
I'm still getting this error with some of my files

**Comment by wader** [comment]
Could you attach an example file?

**Comment by lazaroofarrill** [comment]
Sorry for taking so long.
[2CELLOS - Despacito.mp3.zip](https://github.com/dhowden/tag/files/6555156/2CELLOS.-.Despacito.mp3.zip)
