### ISSUE TITLE
Metadata from some Flac files are empty

### ISSUE THREAD

**Issue by jooola** [dhowden/tag#37]
When I try to read tags from a flac file, they are simply empty, and the File type is wrong : 
![image](https://user-images.githubusercontent.com/19195485/39675788-7e6fc22c-5160-11e8-8c1d-10cf991ad937.png)

![image](https://user-images.githubusercontent.com/19195485/39675792-9a2d0308-5160-11e8-9855-91c8343e7048.png)

**Comment by dhowden** [comment]
Hey!  Thanks for the report.

Can you post the file somewhere (or at least the first few hundred KBs) so that we can have a closer look.

**Comment by jooola** [comment]
Ok this is weird... Maybe I just fixed my problem.
- **Nate** is working out of the box
- **Polo** is not working at all
- **RESAMPLED Polo** is working after re transcoding the using ffmpeg 

![image](https://user-images.githubusercontent.com/19195485/39679067-80d3927c-5198-11e8-99c4-42eb9d6e25b7.png)

https://drop.unixcorn.org/f.php?h=1qvTU4et
https://drop.unixcorn.org/f.php?h=0rwzRt5t
https://drop.unixcorn.org/f.php?h=3gvdXZ5I

Maybe you could tell me what's wrong, I use Puddletag to manage my library's metatags
Tell me if you need any more advanced details !

**Comment by jooola** [comment]
I guess it thinks it is a mp3 file and when trying to get the tags he can't find them.

**Comment by dhowden** [comment]
I've just had a quick look at the "Polo" file using `hexdump`, you can see why the library is picking it up as ID3:

```
$ hexdump -C Polo_\&_Pan_-_01_-_Canopée.flac | head
00000000  49 44 33 04 00 00 00 02  5f 7a 41 50 49 43 00 02  |ID3....._zAPIC..|
00000010  57 52 00 00 00 69 6d 61  67 65 2f 6a 70 65 67 00  |WR...image/jpeg.|
00000020  03 00 ff d8 ff e0 00 10  4a 46 49 46 00 01 01 01  |........JFIF....|
00000030  00 60 00 60 00 00 ff db  00 43 00 08 06 06 07 06  |.`.`.....C......|
00000040  05 08 07 07 07 09 09 08  0a 0c 14 0d 0c 0b 0b 0c  |................|
00000050  19 12 13 0f 14 1d 1a 1f  1e 1d 1a 1c 1c 20 24 2e  |............. $.|
00000060  27 20 22 2c 23 1c 1c 28  37 29 2c 30 31 34 34 34  |' ",#..(7),01444|
00000070  1f 27 39 3d 38 32 3c 2e  33 34 32 ff db 00 43 01  |.'9=82<.342...C.|
00000080  09 09 09 0c 0b 0c 18 0d  0d 18 32 21 1c 21 32 32  |..........2!.!22|
00000090  32 32 32 32 32 32 32 32  32 32 32 32 32 32 32 32  |2222222222222222|
```

**Comment by jooola** [comment]
@dhowden Ok, but isn't FLAC supposed to handle ID3 ? Or is it Vorbis Comment (I don't know much about Vorbis...)

**Comment by jooola** [comment]
Found it !
https://xiph.org/flac/faq.html#general__tagging

I'll rewrite the flac metadata then ! Thanks for your details and method !
