### ISSUE TITLE
Returning "MP3" for FileType of FLAC file

### ISSUE THREAD

**Issue by sincspecv** [dhowden/tag#38]
I have some flac files that show as flac every way I know how to check, but FileType() returns MP3.

**Comment by dhowden** [comment]
Hey!  Thanks for the issue report.  Can you post an example somewhere?

**Comment by sincspecv** [comment]
```
func getFileInfo(file map[string]string) {
	fullPath := file["dir"] + file["name"]
	f, err := os.Open(fullPath)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	var _ io.Reader = (*os.File)(nil)
	// r, err := io.Reader(f)

	// use dhowden/tag to get the tags
	meta, err := tag.ReadFrom(f)
	if err != nil {
		panic(err)
	}
	fmt.Println(fullPath)
	fmt.Println(meta.FileType())
}
```
This function prints
```
/home/dino/Music/Explosions In The Sky/Friday Night Lights/01. Explosions In The Sky - From West Texas.flac
MP3
```
When I check it with mediainfo I get this:
```
General
Complete name                            : 01. Explosions In The Sky - From West Texas.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 9.02 MiB
Duration                                 : 2 min 41 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 469 kb/s
Album                                    : Friday Night Lights
Part                                     : 1
Part/Position                            : 1
Part/Total                               : 1
Track name                               : From West Texas
Track name/Position                      : 01
Track name/Total                         : 14
Performer                                : Explosions In The Sky
Encoded by                               : Exact Audio Copy   (Secure mode)
Genre                                    : Soundtrack
Recorded date                            : 2004
Writing library                          : FLAC.EXE -6 -V -T "ARTIST=Explosions In The Sky" -T "TITLE=From West Texas" -T "ALBUM=Friday Night Lights" -T "DATE=2004" -T "TRACKNUMBER=01" -T "GENRE=Soundtrack" -T "COMMENT=" -T "BAND=" -T "ALBUMARTIST=" -T "COMPOSER=" -T "DISCNUMBER=1" -T "TOTALDISCS=1" -T "TOTALTRACKS=14" --picture="D:\AppData\Local\Temp\CPI53CA.tmp.jpg" -o
Cover                                    : Yes / Yes
Cover description                        : CD Front Cover
Cover type                               : Cover (front) / Cover (front)
Cover MIME                               : image/jpeg / image/jpeg
MCDI                                     : Yes

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 2 min 41 s
Bit rate mode                            : Variable
Bit rate                                 : 464 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 8.93 MiB (99%)
Writing library                          : libFLAC 1.3.1 (UTC 2014-11-25)
```
All other tags seem to be read correctly. If there is some way that I can provide the file in question, I'd be happy to. It does this to all the files on this album.

**Comment by dhowden** [comment]
Sorry, I meant upload the file if you can.  The file type is determined by the first few bytes of the file, so no need to upload the whole thing.

    $ head -c 100 $your_file > header.bin

**Comment by dhowden** [comment]
Also, this issue seems similar to #37, be sure to check that.

**Comment by sincspecv** [comment]
`ID3jTIT2From West TexasTPE1Explosions In The SkyTALBFriday Night LightsTP`

**Comment by sincspecv** [comment]
Upon further review it appears that "fLaC" is in the file, it's just not the first bytes of the file. It looks like the ID3 Tags, followed by a bunch of empty bytes, and then the "fLaC" header. I don't know how hard it would be to find this when determining if it is a flac file or not.

**Comment by dhowden** [comment]
Great work!  Ok so this now seems almost identical to #37.

Lots of tools tend to be very forgiving when reading tag data (due to inconsistencies in early implementations, particularly handling ID3 stuff), which is likely why this is being ignored elsewhere.

The FLAC spec is pretty clear though, so I would recommend checking the encoder you are using, and reporting this. It should not be including the ID3 header (https://xiph.org/flac/faq.html#general__tagging).

**Comment by sincspecv** [comment]
Thanks again for your help. If I found a way to detect a FLAC file with ID3 tags, would you be interested in including it? I was able to write a quick and dirty function that finds the "fLaC" header in the file, though it's not anything I would put in production. I understand if you want to stick to standards.

**Comment by dhowden** [comment]
No problem, thanks for debugging this.

I think that changing the library to support the invalid encoding is probably not worth it,  especially as every correctly ID3 tagged file will have to be checked to see if it’s actually a FLAC file...

However, it’s worth noting the encoding tool used to create the files, just in case others have the same problem.

**Comment by sincspecv** [comment]
Of course. It was encoded using Exact Audio Copy on Windows. It's been so long, I couldn't say if there was an option to use the Vorbis comments or not.

**Comment by dhowden** [comment]
Great, thanks.

I will close the issue for now. If you end up writing a tool to remove the erroneous ID3 data then be sure re-open and post a link here.
