### ISSUE TITLE
Prevent panic when reading mp3 tags and getting ErrNoTags error

### ISSUE THREAD

**Issue by jooola** [dhowden/tag#42]
I think we should simply return empty string and 0 when a value is not found.

The problem is that for mp3 files, if they have no tags, parser will return ErrNoTags and if we try to access some metadata we get a panic because data doesn't exist.

**Comment by dhowden** [comment]
In the current implementation it is straightforward to distinguish between the cases "no tag data found" (i.e. when non present, or the tag format of the file is not known) and "tag data found, all values empty".  This is particularly important in the case where the tag format is not known: we do not want to give back data that is unreliable.

In any case, the returned error should always be checked and if non-nil the metadata return argument should assumed to be nil (as is the Go convention).

Closing for now, feel free to re-open if you want to discuss further.
