### ISSUE TITLE
flac.parseStreamInfo: invalid FLAC signature

### ISSUE THREAD

**Issue by grand0rbiter** [dhowden/tag#55]
I'm getting flac.parseStreamInfo: invalid FLAC signature; expected "fLaC", got "\xff\xf8\xcb\x1c"

Here is the entire function:

    func listFiles() ([]string, error) {
        searchDir := "./"

        fileList := []string{}
        err := filepath.Walk(searchDir, func(path string, f os.FileInfo, err error) error {
                if err != nil {
                        log.Fatal(err)
                }
                fileList = append(fileList, path)
                return nil
        })

        for _, file := range fileList {
                if filepath.Ext(file) == ".flac" {
                        fmt.Println(file)
                        f, err := os.Open(file)
                        m, _ := tag.ReadFrom(f)
                        log.Print(m.Title())
                        streamer, format, err := flac.Decode(f)
                        if err != nil {
                                log.Fatal(err)
                        }
                        defer streamer.Close()

                        speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))

                        done := make(chan bool)

                        speaker.Play(beep.Seq(streamer, beep.Callback(func() {
                                done <- true
                        })))
                        <-done
                }
        }
        return fileList, err
    }

What am i doing wrong? It happens with different flac files from different albums.

**Comment by wader** [comment]
Looks like the flac decoder get the first flac frame instead of a flac header and a streaminfo block. My guess is that if you want to reuse the file `f` as a reader you have to seek back to the start of the file after `tag.ReadFrom(f)` before giving it to `flac.Decode(f)`.

**Comment by dhowden** [comment]
@awader is correct. `ReadFrom` will not reset the `io.ReadSeeker` (so the `*os.File` `f` in this case) once it has finished reading the tag information.

Adding
```golang
if _, err = f.Seek(0, io.SeekStart); err != nil {
    // handle err
}
```
to reset back to the beginning of `f` before your call to `flac.Decode(f)` should fix this.

**Comment by grand0rbiter** [comment]
Thanks! It works now.
