### ISSUE TITLE
Cannot extract metadata from OGG file

### ISSUE THREAD

**Issue by deluan** [dhowden/tag#67]
(Sorry for bombarding you with issues, but this is the best pure Go tag library out there and this is my way of contributing to make it even better! Thanks for your awesome job!)

I think the way that the picture is embedded in this file is breaking the library. This is what I get:
```
$ tag Indila.ogg
error reading file: unexpected EOF
```
[Indila.ogg.zip](https://github.com/dhowden/tag/files/4463985/Indila.ogg.zip)

I think it may be caused by the way the picture is embedded. Normally ffmpeg reports the embedded art as a separated stream like this:
```
    Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 700x700 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
``` 

But in the attached file, it appears as a tag of the audio stream:
```
    Stream #0:0(fra): Audio: vorbis, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      metadata_block_picture: AAAAAwAAAAppbWFnZS9qcGVnAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5FA/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
```

**Comment by wader** [comment]
Seems to work with #65 

Interesting, seem to work with ffmpeg 4.1.3 but not ffmpeg 4.2.0. Maybe some regression, ill see if i can find something.

**Comment by wader** [comment]
I think this https://github.com/FFmpeg/FFmpeg/commit/8d3630c5402fdda2889fe4f74f7dcdd50ebca654 broke it in ffmpeg. The `strcmp(tt, "METADATA_BLOCK_PICTURE")` was not updated properly to `av_strncasecmp(tt, "METADATA_BLOCK_PICTURE")`

**Comment by wader** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200411094625.7677-1-mattias.wadman@gmail.com/

**Comment by wader** [comment]
Merged in to ffmpeg master now, that was fast. Seems like there was more ppl noticing this https://trac.ffmpeg.org/ticket/8608 good find

**Comment by dhowden** [comment]
Thanks @wader :-).

@deluan No worries. I built this library to support my own music player/streaming (https://github.com/tchaik/tchaik) so I know where you're coming from :-)
