### ISSUE TITLE
Error in Cover Art extraction

### ISSUE THREAD

**Issue by mobedoor** [dhowden/tag#75]
Hello. 
The package fails to extract cover art from the following file
[02 path of the wind.zip](https://github.com/dhowden/tag/files/5264819/02.path.of.the.wind.zip)

**Comment by wader** [comment]
There is a WCOP tag with a zero size field that for some reason tag see as end of tags https://github.com/dhowden/tag/blob/master/id3v2.go#L260 which is not the case. Maybe that condition should actually look if the name is padding zero bytes somehow as i think a zero field is ok.
