### ISSUE TITLE
Installation instructions in README are outdated ("go get" is deprecated)

### ISSUE THREAD

**Issue by AntoineBalaine** [dhowden/tag#85]
Hello,

I can't install the package with : 
`$ go get github.com/dhowden/tag/...` because using "go get" is apparently deprecated.
I also tried `$ go install github.com/dhowden/tag` and `$ go install github.com/dhowden/tag@latest` but neither works.

Could you please provide clarification for the install?

**Comment by dhowden** [comment]
Hi!  Which version of Go are you using?

**Comment by AntoineBalaine** [comment]
I’m using go 1.17.1 darwin/amd64

**Comment by dhowden** [comment]
Ok, found this https://golang.org/doc/go-get-install-deprecation

I would think you need to do:

```lang=shell
$ go get install github.com/dhowden/tag/cmd/tag
```

(to install the `tag` command line tool).  Can you try it out?
